services:
  fiagram_mysql:
    image: mysql:9.5.0
    container_name: fiagram_mysql-0
    restart: always
    ports:
      - "11000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiagram
    volumes:
      - fiagram_mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  fiagram_redis:
    image: redis:8.4.0
    container_name: fiagram_redis-0
    restart: always

  fiagram_standalone:
    image: fiagram_standalone:0.0.0
    container_name: fiagram_standalone-0
    restart: always
    ports:
      - "11001:11001"
    volumes:
      - ./configs/test.yaml:/home/test.yaml:ro
    command: /standalone -c /home/test.yaml
    depends_on:
      fiagram_mysql:
        condition: service_healthy
      fiagram_redis:
        condition: service_started

volumes:
  fiagram_mysql_data:

networks:
  default:
    name: fiagram_network
