http:
  address: 0.0.0.0
  port: 11001
  CORS:
    isEnable: true
    allowOrigins:
      - "http://localhost:3000"
      - "https://fiagram.io.vn"
      - "https://app.fiagram.io.vn"
    allowMethods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowHeaders:
      - Origin
      - Content-Type
      - Authorization
    exposeHeaders:
      - Content-Length
    allowCredentials: true
    maxAge: 12h
  cookie:
    domain: localhost
    path: "/"
    sameSite: none
    secure: true
    httpOnly: true

message_queue:
  addresses:
    - fiagram_kafka-0:9092
  clientID: standalone

auth:
  hash:
    cost: 10
  token:
    secret: secret_token_in_here
    accessTokenTTL: 15m
    refreshTokenTTL: 24h
    refreshTokenLongTTL: 720h

log:
  level: debug

database_client:
  type: mysql
  address: fiagram_mysql-0
  port: 3306
  username: root
  password: root
  database: fiagram

cache_client:
  type: redis
  address: fiagram_redis-0
  port: 6379
  username:
  password:

sepay:
  api_key: "test_sepay_api_key"
  account_number: "test_bank_account_number"
  bank_code: "MB"
  webhook_secret: "test_webhook_secret"
  payment_expiry: 15m
