http:
  address: 0.0.0.0
  port: 8080

auth:
  domain: localhost
  hash:
    cost: 10
  token:
    secret: secret_token_in_here
    accessTokenTTL: 15m
    refreshTokenTTL: 24h
    refreshTokenLongTTL: 720h

database:
  type: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  name: db_fiagram

cache:
  type: redis
  address: 127.0.0.1
  port: 6379
  username:
  password:

log:
  level: debug
